force-app/main/default/objects/Slack_Channel__c/Slack_Channel__c.object-meta.xml
<CustomObject>
    <description>A slack channel where you can post messages to using flows or apex.</description>
    <label>Slack Channel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slack Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Message__c/Slack_Message__c.object-meta.xml
<CustomObject>
    <description>A message you want to send to slack. Once it&apos;s created, it will be sent immediately to the channel that you specified.</description>
    <label>Slack Message</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Message__c/fields/Slack_Channel__c.field-meta.xml
<CustomField>
    <fullName>Slack_Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The channel you want to send the message to.</description>
    <label>Slack Channel</label>
    <referenceTo>Slack_Channel__c</referenceTo>
    <relationshipLabel>Slack Messages</relationshipLabel>
    <relationshipName>Slack_Messages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SlackTestDataFactory_Test.cls
@isTest
public class SlackTestDataFactory_Test {
    @isTest static void testSlackTestDataFactory() {
        Test.startTest();
        SlackTestDataFactory.generateTestData();
        Slack_Channel__c slackChannel = SlackTestDataFactory.createSlackChannel();
        Slack_Message__c slackMessage = SlackTestDataFactory.createSlackMessage(slackChannel, false);
        Test.stopTest();
        System.assert(slackChannel != null);
        System.assert(slackMessage != null);
    }
}