force-app/main/default/objects/Slack_App__c/Slack_App__c.object-meta.xml
<CustomObject>
    <label>Slack App</label>
    <nameField>
        <label>Slack App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slack Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_App__c/fields/App_ID__c.field-meta.xml
<CustomField>
    <fullName>App_ID__c</fullName>
    <externalId>true</externalId>
    <label>App ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Slack_App__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <label>Site_URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Slack_Channel__c/Slack_Channel__c.object-meta.xml
<CustomObject>
    <description>A slack channel where you can post messages to using flows or apex.</description>
    <label>Slack Channel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slack Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Channel__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Slack_Channel__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <description>The endpoint URL for incoming webhook messages for this channel</description>
    <externalId>true</externalId>
    <inlineHelpText>The endpoint URL for incoming webhook messages for this channel</inlineHelpText>
    <label>Endpoint URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Slack_Home__c/Slack_Home__c.object-meta.xml
<CustomObject>
    <label>Slack Home</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Slack Home Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Homes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Home__c/fields/Home__c.field-meta.xml
<CustomField>
    <fullName>Home__c</fullName>
    <label>Home</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Slack_Message__c/Slack_Message__c.object-meta.xml
<CustomObject>
    <description>A message you want to send to slack. Once it&apos;s created, it will be sent immediately to the channel that you specified.</description>
    <label>Slack Message</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The message you want to send to Slack, in JSON format, created in the Slack Block Kit Builder.</description>
    <inlineHelpText>The message you want to send to Slack, in JSON format, created in the Slack Block Kit Builder.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Slack_Message__c/fields/Only_visible_to_you__c.field-meta.xml
<CustomField>
    <fullName>Only_visible_to_you__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want to send a &quot;Only visible to you&quot; Slack message, which is only visible for one slack user, not for the rest of the channel.</description>
    <inlineHelpText>Check this if you want to send a &quot;Only visible to you&quot; Slack message, which is only visible for one slack user, not for the rest of the channel.</inlineHelpText>
    <label>Hidden Message?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Slack_Message__c/fields/Slack_Channel__c.field-meta.xml
<CustomField>
    <fullName>Slack_Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The channel you want to send the message to.</description>
    <label>Slack Channel</label>
    <referenceTo>Slack_Channel__c</referenceTo>
    <relationshipLabel>Slack Messages</relationshipLabel>
    <relationshipName>Slack_Messages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slack_Message__c/fields/Thread_ID__c.field-meta.xml
<CustomField>
    <fullName>Thread_ID__c</fullName>
    <description>The ID of an existing Slack Thread, if you want to send your message as a reply to a specific thread.</description>
    <inlineHelpText>The ID of an existing Slack Thread, if you want to send your message as a reply to a specific thread.</inlineHelpText>
    <label>Thread ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Slack_Modal__c/Slack_Modal__c.object-meta.xml
<CustomObject>
    <label>Slack Modal</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Slack Modal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Modals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Modal__c/fields/Modal__c.field-meta.xml
<CustomField>
    <fullName>Modal__c</fullName>
    <label>Modal</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Slack_Modal__c/fields/Trigger_ID__c.field-meta.xml
<CustomField>
    <fullName>Trigger_ID__c</fullName>
    <label>Trigger ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SlackTestDataFactory.cls
public class SlackTestDataFactory {

    public static void generateTestData() {
        Slack_App__c slackApp = createSlackApp();
        Slack_Channel__c slackChannel = createSlackChannel();
        insert slackApp;
        insert slackChannel;
    }

    public static Slack_App__c createSlackApp() {
        Slack_App__c slackApp = new Slack_App__c(
            Name = 'testName',
            Site_URL__c = 'testUrl',
            App_ID__c = 'testAppId',
            Client_ID__c = 'clientId',
            Client_Secret__c = 'clientSecret'
        );
        
        return slackApp;
    }

    public static Slack_Channel__c createSlackChannel() {
        Slack_Channel__c slackChannel = new Slack_Channel__c(
         Name = 'testChannel',
         Endpoint_URL__c = 'testEndpoint',
         Access_Token__c = 'testAccessToken'   
        );

        return slackChannel;
    }

    public static Slack_Message__c createSlackMessage(Slack_Channel__c slackChannel, Boolean ephemeralMessage) {
        Slack_Message__c slackMessage = new Slack_Message__c(
            Message__c ='{ "blocks": [ { "type": "section", "text": { "type": "mrkdwn", "text": "Test Message" } } ] }',
            Slack_Channel__c = slackChannel.Id,
            Thread_ID__c = 'test',
            Only_visible_to_you__c = ephemeralMessage
        );
        return slackMessage;
    }

    public static Slack_Modal__c createSlackModal() {
        Slack_Modal__c slackModal = new Slack_Modal__c(
            Modal__c = '',
            Trigger_ID__c = 'test'
        );
        return slackModal;
    }

    public static Slack_Home__c createSlackHome() {
        Slack_Home__c slackHome = new Slack_Home__c(
            Home__c = ''
        );
        return slackHome;
    }

}