force-app/main/default/objects/Slack_App__c/Slack_App__c.object-meta.xml
<CustomObject>
    <label>Slack App</label>
    <nameField>
        <label>Slack App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slack Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Channel__c/Slack_Channel__c.object-meta.xml
<CustomObject>
    <description>A slack channel where you can post messages to using flows or apex.</description>
    <label>Slack Channel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slack Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Channel__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Slack_Channel__c/fields/Channel_ID__c.field-meta.xml
<CustomField>
    <fullName>Channel_ID__c</fullName>
    <label>Channel ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Slack_Channel__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <description>The endpoint URL for incoming webhook messages for this channel</description>
    <externalId>true</externalId>
    <inlineHelpText>The endpoint URL for incoming webhook messages for this channel</inlineHelpText>
    <label>Endpoint URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Slack_Home__c/Slack_Home__c.object-meta.xml
<CustomObject>
    <label>Slack Home</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Slack Home Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Homes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Home__c/fields/Home__c.field-meta.xml
<CustomField>
    <fullName>Home__c</fullName>
    <label>Home</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Slack_Message__c/Slack_Message__c.object-meta.xml
<CustomObject>
    <description>A message you want to send to slack. Once it&apos;s created, it will be sent immediately to the channel that you specified.</description>
    <label>Slack Message</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The message you want to send to Slack, in JSON format, created in the Slack Block Kit Builder.</description>
    <inlineHelpText>The message you want to send to Slack, in JSON format, created in the Slack Block Kit Builder.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Slack_Message__c/fields/Only_visible_to_you__c.field-meta.xml
<CustomField>
    <fullName>Only_visible_to_you__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want to send a &quot;Only visible to you&quot; Slack message, which is only visible for one slack user, not for the rest of the channel.</description>
    <inlineHelpText>Check this if you want to send a &quot;Only visible to you&quot; Slack message, which is only visible for one slack user, not for the rest of the channel.</inlineHelpText>
    <label>Hidden Message?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Slack_Message__c/fields/Slack_Channel__c.field-meta.xml
<CustomField>
    <fullName>Slack_Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The channel you want to send the message to.</description>
    <label>Slack Channel</label>
    <referenceTo>Slack_Channel__c</referenceTo>
    <relationshipLabel>Slack Messages</relationshipLabel>
    <relationshipName>Slack_Messages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slack_Message__c/fields/Thread_ID__c.field-meta.xml
<CustomField>
    <fullName>Thread_ID__c</fullName>
    <description>The ID of an existing Slack Thread, if you want to send your message as a reply to a specific thread.</description>
    <inlineHelpText>The ID of an existing Slack Thread, if you want to send your message as a reply to a specific thread.</inlineHelpText>
    <label>Thread ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Slack_Modal__c/Slack_Modal__c.object-meta.xml
<CustomObject>
    <label>Slack Modal</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Slack Modal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Modals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Modal__c/fields/Modal__c.field-meta.xml
<CustomField>
    <fullName>Modal__c</fullName>
    <label>Modal</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Slack_Modal__c/fields/Trigger_ID__c.field-meta.xml
<CustomField>
    <fullName>Trigger_ID__c</fullName>
    <label>Trigger ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SlackActions.cls
public class SlackActions {
    
    // Updating Home
    @future(callout=true)
    public static void sendHomeToSlackAsync(Id slackHomeId) {
        sendHomeToSlack(slackHomeId);
    }


    public static String sendHomeToSlack(Id slackHomeId) {
        Slack_Home__c slackHome = [SELECT Home__c FROM Slack_Home__c WHERE Id = :slackHomeId];

        // Select the first (and presumably only SlackApp available)
        Slack_App__c slackApp = [SELECT Access_Token__c, User_ID__c FROM Slack_App__c LIMIT 1];

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://slack.com/api/views.publish');
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Authorization', 'Bearer ' + slackApp.Access_Token__c);
        String message = '{"user_id" : "' + slackApp.User_ID__c + '", "view" : ' + slackHome.Home__c + '}';
        request.setBody(message);

        try {
            HttpResponse res = http.send(request);
            System.debug(res.getBody());
            if (res.getStatusCode() >= 200 && res.getStatusCode() < 300) {
                return 'Message Sent Succesfully';
            } else {
                return 'The request worked, but we got a bad status code back, the status code is ' + res.getStatusCode();
            }
        }
        catch (CalloutException e) {
            return e.getMessage();
        }

    }

    // Sending Modals
    @future(callout=true)
    public static void sendModalToSlackAsync(Id slackModalId) {
        sendModalToSlack(slackModalId);
    }


    public static String sendModalToSlack(Id slackModalId) {
        Slack_Modal__c slackModal = [SELECT Modal__c, Trigger_ID__c FROM Slack_Modal__c WHERE Id = :slackModalId];
        Slack_App__c slackApp = [SELECT Access_Token__c, User_ID__c FROM Slack_App__c LIMIT 1];
        String modal = slackModal.Modal__c;

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://slack.com/api/views.open');
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Authorization', 'Bearer ' + slackApp.Access_Token__c);
        String message = '{"trigger_id" : "' + slackModal.Trigger_ID__c + '", "view" : ' + slackModal.Modal__c + '}';
        request.setBody(message);

        try {
            HttpResponse res = http.send(request);
            System.debug(res.getBody());
            if (res.getStatusCode() >= 200 && res.getStatusCode() < 300) {
                return 'Message Sent Succesfully';
            } else {
                return 'The request worked, but we got a bad status code back, the status code is ' + res.getStatusCode();
            }
        }
        catch (CalloutException e) {
            return e.getMessage();
        }

    }

    // Sending Messages

    @future(callout=true)
    public static void sendMessageToSlackAsync(Id slackMessageId) {
        sendMessageToSlack(slackMessageId);
    }

    public static String sendMessageToSlack(Id slackMessageId) {
        Slack_Message__c slackMessage = [SELECT Message__c, Slack_Channel__c, Only_visible_to_you__c, Thread_ID__c FROM Slack_Message__c WHERE Id = :slackMessageId];
        Slack_Channel__c slackChannel = [SELECT Endpoint_URL__c, Access_Token__c, User_ID__c, Channel_ID__c FROM Slack_Channel__c WHERE Id = :slackMessage.Slack_Channel__c];
        String endpoint = slackChannel.Endpoint_URL__c;
        String message = slackMessage.Message__c;

        // Check if it's a reply to a threads
        if(slackMessage.Thread_ID__c != null) {
            String addToMessage = '"thread_ts" : "' + slackMessage.Thread_ID__c + '",';
            message = message.substring(0,1) + addToMessage + message.substring(1);
        }

        // Indien geen ephemeral message
        if(slackMessage.Only_visible_to_you__c == false) {
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endpoint);
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setBody(message);
            System.debug(message);

            try {
                HttpResponse res = http.send(request);
                System.debug(res.getBody());
                if (res.getStatusCode() >= 200 && res.getStatusCode() < 300) {
                    return 'Message Sent Succesfully';
                } else {
                    return 'The request worked, but we got a bad status code back, the status code is ' + res.getStatusCode();
                }
            }
            catch (CalloutException e) {
                return e.getMessage();
            }

        // Indien wel ephemeral message
        } else {
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('https://slack.com/api/chat.postEphemeral');
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setHeader('Authorization', 'Bearer ' + slackChannel.Access_Token__c);
            String addToMessage = '"user": "' + slackChannel.User_ID__c + '", "channel" : "' + slackChannel.Channel_ID__c + '",';
            String newMessage = message.substring(0,1) + addToMessage + message.substring(1);

            request.setBody(newMessage);

            try {
                HttpResponse res = http.send(request);
                if (res.getStatusCode() >= 200 && res.getStatusCode() < 300) {
                    return 'Message Sent Succesfully';
                } else {
                    return 'The request worked, but we got a bad status code back, the status code is ' + res.getStatusCode();
                }
            }
            catch (CalloutException e) {
                return e.getMessage();
            }
        }
    }
}