force-app/main/default/objects/Slack_App__c/Slack_App__c.object-meta.xml
<CustomObject>
    <label>Slack App</label>
    <nameField>
        <label>Slack App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slack Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Channel__c/Slack_Channel__c.object-meta.xml
<CustomObject>
    <description>A slack channel where you can post messages to using flows or apex.</description>
    <label>Slack Channel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slack Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Home__c/Slack_Home__c.object-meta.xml
<CustomObject>
    <label>Slack Home</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Slack Home Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Homes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Message__c/Slack_Message__c.object-meta.xml
<CustomObject>
    <description>A message you want to send to slack. Once it&apos;s created, it will be sent immediately to the channel that you specified.</description>
    <label>Slack Message</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Message__c/fields/Slack_Channel__c.field-meta.xml
<CustomField>
    <fullName>Slack_Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The channel you want to send the message to.</description>
    <label>Slack Channel</label>
    <referenceTo>Slack_Channel__c</referenceTo>
    <relationshipLabel>Slack Messages</relationshipLabel>
    <relationshipName>Slack_Messages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slack_Modal__c/Slack_Modal__c.object-meta.xml
<CustomObject>
    <label>Slack Modal</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Slack Modal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Modals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SlackActions_Test.cls
@isTest
public class SlackActions_Test {

    @isTest static void testCreateSlackChannel() {
        Slack_App__c slackApp = SlackTestDataFactory.createSlackApp();
        Slack_Channel__c slackChannel = SlackTestDataFactory.createSlackChannel();
        insert slackApp;
        insert slackChannel;

        String slackChannelName = 'Test Channel Name';

        Test.setMock(HttpCalloutMock.class, new SlackHttpCalloutMockCreateChannel()); 
        Test.startTest();
            SlackActions.createSlackChannelAsync(slackChannelName);
        Test.stopTest();
    }

    @isTest static void testSendSlackModal() {
        Slack_App__c slackApp = SlackTestDataFactory.createSlackApp();
        Slack_Channel__c slackChannel = SlackTestDataFactory.createSlackChannel();
        insert slackApp;
        insert slackChannel;

        Test.setMock(HttpCalloutMock.class, new SlackHttpCalloutMock()); 
        Test.startTest();
            Slack_Modal__c slackModal = SlackTestDataFactory.createSlackModal();
            insert slackModal;
        Test.stopTest();
    }

    @isTest static void testSendSlackHome() {
        Slack_App__c slackApp = SlackTestDataFactory.createSlackApp();
        Slack_Channel__c slackChannel = SlackTestDataFactory.createSlackChannel();
        insert slackApp;
        insert slackChannel;

        Test.setMock(HttpCalloutMock.class, new SlackHttpCalloutMock()); 
        Test.startTest();
            Slack_Home__c slackHome = SlackTestDataFactory.createSlackHome();
            insert slackHome;
        Test.stopTest();
    }

   @isTest static void testSendSlackMessageEphemeral() {

    Slack_App__c slackApp = SlackTestDataFactory.createSlackApp();
    Slack_Channel__c slackChannel = SlackTestDataFactory.createSlackChannel();
    insert slackApp;
    insert slackChannel;

    Test.setMock(HttpCalloutMock.class, new SlackHttpCalloutMockEphemeral());   
    Test.startTest();
        Slack_Message__c slackMessage = SlackTestDataFactory.createSlackMessage(slackChannel, true);
        insert slackMessage;
    Test.stopTest();
   }

   @isTest static void testSendSlackMessageWebhook() {
    Slack_App__c slackApp = SlackTestDataFactory.createSlackApp();
    Slack_Channel__c slackChannel = SlackTestDataFactory.createSlackChannel();
    insert slackApp;
    insert slackChannel;

    Test.setMock(HttpCalloutMock.class, new SlackHttpCalloutMock()); 
    Test.startTest();
        Slack_Message__c slackMessage = SlackTestDataFactory.createSlackMessage(slackChannel, false);
        insert slackMessage;
    Test.stopTest();
   }

    public class SlackHttpCalloutMockEphemeral implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest request) {
            // Create a fake response
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{ "ok": true, "message_ts": "1502210682.580145" }}');
            response.setStatusCode(200);
            return response; 
        }
    }

    public class SlackHttpCalloutMock implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest request) {
            // Create a fake response
            HttpResponse response = new HttpResponse();
            response.setBody('ok');
            response.setStatusCode(200);
            return response; 
        }
    }

    public class SlackHttpCalloutMockCreateChannel implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest request) {
            // Create a fake response
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{ "channel": {"name" : "testName", "id" : "testId", "creator" : "creatorId"}, "ok" : true}');
            response.setStatusCode(200);
            return response; 
        }
    }
}